FROM node:14.17.5-alpine3.12

ENV APP_ROOT /var/www

RUN mkdir -p $APP_ROOT

RUN apk update && \
  apk add git bash && \
  npm i -g create-react-app jshint

COPY package.json $APP_ROOT
COPY package-lock.json $APP_ROOT

WORKDIR $APP_ROOT

RUN npm install

COPY . $APP_ROOT

EXPOSE 8000

# CMD [ "npm", "run", "dev" ]
